[mgr]
prepend_keymap = [
	# { on = "<ESC>", run = "quit", desc = "Quit" },
	{ on = "<Enter>", run = "enter", desc = "Enter directory (don't open)" },
	{ on = "o", run = "open", desc = "Open file/directory" },
	{ on = ["g", "."], run = "cd ~/.dotfiles", desc = "Open Dotfiles" },
	{ on = ["g", "G"], run = "cd ~/Git", desc = "Open git directory" },
	{ on = ["g", "n"], run = "cd ~/General", desc = "Open general directory" },
	{ on = ["g", "s"], run = "cd ~/Staging", desc = "Open staging directory" },
]
