---
- name: Install and set Arch Linux console font
  hosts: all
  become: true
  tasks:
    - name: Install terminus-font package
      community.general.pacman:
        name: terminus-font
        state: present
        update_cache: true

    - name: Set console font in /etc/vconsole.conf
      ansible.builtin.lineinfile:
        path: /etc/vconsole.conf
        regexp: '^FONT='
        line: 'FONT=ter-d32b.psf.gz'
        state: present
      notify: Reload vconsole.conf

  handlers:
    - name: Reload vconsole.conf
      ansible.builtin.command: systemctl restart systemd-vconsole-setup.service
      listen: "Reload vconsole.conf"