---
- name: Install Extra Tooling
  hosts: localhost
  become: true # Necessary to run with root privileges

  vars_prompt:
    - name: install_kitty
      prompt: "Install Kitty? (n/y)"
      default: "no"
      private: no
    - name: install_zenith
      prompt: "Install Zenith? (n/y)"
      default: "no"
      private: no
    - name: install_cull
      prompt: "Install Cull? (n/y)"
      default: "no"
      private: no
    - name: install_caligula
      prompt: "Install Caligula? (n/y)"
      default: "no"
      private: no
    - name: install_firefox
      prompt: "Install Firefox? (n/y)"
      default: "no"
      private: no
    - name: install_bitwarden
      prompt: "Install Bitwarden? (n/y)"
      default: "no"
      private: no

  tasks:
    - name: Install Kitty
      community.general.pacman:
        name: kitty
        state: present
        update_cache: true
      when: install_kitty | bool

    - name: Install Zenith (System Resource Monitor)
      community.general.pacman:
        name: zenith
        state: present
        update_cache: true
      when: install_zenith | bool

    - name: Install Cull (Disk Usage Analyzer)
      yay:
        name: cull-bin
        state: present
      when: install_cull | bool

    - name: Install Caligula (Disk Imager)
      community.general.pacman:
        name: caligula
        state: present
        update_cache: true
      when: install_caligula | bool

    - name: Install Firefox
      community.general.pacman:
        name: firefox
        state: present
        update_cache: true
      when: install_firefox | bool

    - name: Install Bitwarden
      community.general.pacman:
        name: bitwarden
        state: present
        update_cache: true
      when: install_bitwarden | bool
