---
- name: Install Nerd Font
  hosts: localhost
  become: true
  tasks:
    - name: Install Symbols Nerd Font Mono
      community.general.pacman:
        name: ttf-nerd-font-symbols-common
        state: present
        update_cache: true
