---
- name: Install Nerd Font
  hosts: localhost
  become: true
  tasks:
    - name: Install FiraCode Nerd Font
      community.general.pacman:
        name:
          - ttf-firacode-nerd
          - ttf-nerd-fonts-symbols-common
        state: present
        update_cache: true
