---
- name: Install Hyprland and Essential Wayland Tooling
  hosts: localhost
  become: true # Necessary to run with root privileges

  tasks:
    - name: Install Hyprland and Portals
      community.general.pacman:
        name:
          - hyprland
        state: present
        update_cache: true

    - name: Install Waybar
      community.general.pacman:
        name:
          - waybar
        state: present
        update_cache: true

    - name: Install Launcher
      community.general.pacman:
        name:
          - wofi
        state: present
        update_cache: true

    - name: Install Hyprshot
      community.general.pacman:
        name:
          - hyprshot
        state: present
        update_cache: true

    - name: Install Sway Notification Center
      community.general.pacman:
        name:
          - swaync
        state: present
        update_cache: true

    - name: Install Hyprlock
      community.general.pacman:
        name:
          - hyprlock
        state: present
        update_cache: true

    - name: Install Hypridle
      community.general.pacman:
        name:
          - hypridle
        state: present
        update_cache: true
