---
- name: Install Hyprland and Essential Wayland Tooling
  hosts: localhost
  become: true # Necessary to run with root privileges

  tasks:
    - name: Install Hyprland and Portals
      community.general.pacman:
        name:
          - hyprland
        state: present
        update_cache: true

    - name: Install Waybar
      community.general.pacman:
        name:
          - waybar
        state: present
        update_cache: true

    - name: Install Launcher
      community.general.pacman:
        name:
          - wofi
        state: present
        update_cache: true

    - name: Install Hyprshot
      community.general.pacman:
        name:
          - hyprshot
        state: present
        update_cache: true

    - name: Install Sway Notification Center
      community.general.pacman:
        name:
          - swaync
        state: present
        update_cache: true

    - name: Install Hypr Lock
      community.general.pacman:
        name:
          - hyprlock
        state: present
        update_cache: true

    - name: Install Hypr Idle
      community.general.pacman:
        name:
          - hypridle
        state: present
        update_cache: true

    - name: Install Hypr Paper
      community.general.pacman:
        name:
          - hyprpaper
        state: present
        update_cache: true

    - name: Install GNOME Themes Extra for Dark Mode Support
      community.general.pacman:
        name:
          - gnome-themes-extra
        state: present
        update_cache: true

    - name: Set Dark Color Scheme
      ansible.builtin.command:
        cmd: gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
      become: false
      changed_when: false

    - name: Install Ly Display Manager
      community.general.pacman:
        name:
          - ly
        state: present
        update_cache: true

    - name: Enable Ly Display Manager
      ansible.builtin.command:
        cmd: systemctl enable --now ly@tty1.service
      changed_when: true
