---
- name: Install NVIDIA Drivers (Minimal)
  hosts: localhost
  become: true

  tasks:
    - name: Install NVIDIA Drivers
      community.general.pacman:
        name:
          - nvidia-open
          - nvidia-settings
          - nvidia-utils
          - lib32-nvidia-utils
        state: present
        update_cache: true

    - name: Install EGL Wayland Support
      community.general.pacman:
        name:
          - egl-wayland
        state: present
        update_cache: true

    - name: Install Vulkan Support
      community.general.pacman:
        name:
          - vulkan-headers
          - vulkan-tools
          - lib32-vulkan-icd-loader
        state: present
        update_cache: true
